package acted.core.security

/**
 * Created by raoul on 30/10/14.
 */
enum RoleEnum {
    COUNTRY_LOGISTICS_MANAGER,
    DEPUTY_LOGISTICS_MANAGER,
    DEPUTY_PROCUREMENT_MANAGER,
    CAPITAL_LOGISTICS_OFFICER,
    CAPITAL_LOGISTICS_ASSISTANT,
    CAPITAL_PROCUREMENT_OFFICER,
    CAPITAL_TRANSPORT_OFFICER,
    CAPITAL_IT_COMMUNICATION_OFFICER,
    AREA_LOGISTICS_OFFICER,
    AREA_LOGISTICS_ASSISTANT,
    AREA_PROCUREMENT_OFFICER,
    AREA_TRANSPORT_OFFICER,
    STOREKEEPER,
    RADIO_OPERATOR,
    SECURITY_GUARDS,
    MECHANIC,
    DRIVER,
    FLYING_WORKER,
    POUCH_MAN
}